name: CI

on:
  pull_request:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ github.event_name }}
          echo ${{ toJson(github.event) }}
          echo ${{ github.event.head.repo.id }}
          echo ${{ github.event.head.repo.full_name }}
          echo ${{ github.event.base.repo.id }}
          echo ${{ github.event.base.repo.full_name }}
